# This file has been generated by node2nix 1.5.3. Do not edit!

{pkgs ? import <nixpkgs> {}, nodejs ? pkgs."nodejs-8_x"}:

with pkgs;

stdenv.mkDerivation {
  name = "nodeTools";
  buildInputs = [ nodejs ];

  src = builtins.filterSource (path: type:
    type != "unknown" &&
    baseNameOf path != "node_modules" &&
    baseNameOf path != "result" &&
    baseNameOf path != "upgrade.sh" &&
    baseNameOf path != "default.nix" &&
    baseNameOf path != "npm.log"
  ) ./.;

  buildPhase = ''
    echo 1111
    HOME=$PWD npm install
  '';

  installPhase = ''
    mkdir $out
    cp -r ./ $out/
    ln -s $out/node_modules/.bin $out/bin
  '';
}

