# This file has been generated by node2nix 1.5.3. Do not edit!

{pkgs ? import <nixpkgs> {}, nodejs ? pkgs."nodejs-8_x"}:

with pkgs;

stdenv.mkDerivation {
  name = "nodeTools";
  buildInputs = [ nodejs ];

  src = builtins.filterSource (path: type:
    type != "unknown" &&
    baseNameOf path != "node_modules" &&
    baseNameOf path != "result" &&
    baseNameOf path != "upgrade.sh" &&
    baseNameOf path != "default.nix" &&
    baseNameOf path != "npm.log" &&
    baseNameOf path != ".gitignore"
  ) ./.;

  buildPhase = ''
    HOME=$PWD npm install
  '';

  installPhase = ''
    mkdir -p $out/nodeTools
    cp -r node_modules $out/nodeTools/
    ln -s $out/nodeTools/node_modules/.bin $out/bin
  '';
}

