name = "trains"
version = "0.1.0"
defaultTargets = ["trains"]

[[lean_lib]]
name = "Trains"

[[lean_exe]]
name = "trains"
root = "Main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "31a10a3328"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser.git"
rev = "main"

[[require]]
scope = "lecopivo"
name = "scilean"
rev = "53f112d"
