[project]
name = "trains"
version = "0.1.0"
description = "A web-based railroad game built with NiceGUI"
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.0",
    "nicegui>=3.12.1",
    "aiohttp",
    "requests>=2.0",
    "urllib3>=1.0,<2.0",
    "geojson-pydantic",
    "shapely",
    "ty",
    "pytest",
    "pytest-asyncio",
    "types-requests>=2.0",
]

[project.scripts]
trains-server = "trains.server:main"
trains-map-viewer = "trains.map:main"

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/trains"]

[tool.hatch.build.targets.wheel.force-include]
"src/trains/canada.json" = "trains/canada.json"
"src/trains/mexico.json" = "trains/mexico.json"
"src/trains/ne_50m_lakes.json" = "trains/ne_50m_lakes.json"
"src/trains/rivers_50_na.json" = "trains/rivers_50_na.json"
"src/trains/rivers_na.json" = "trains/rivers_na.json"
"src/trains/usa.json" = "trains/usa.json"
