# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "38s4f3id97wsb0rg9nm9zvxyq0nvwrmrpa5dzvrkp36mf5ibs98b4z6lvsbrwzzs0sbcank6c7gpp06vcwp9acfhp41rzlhi3ybsxwy";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "bluebird-3.5.1" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.1.tgz";
        sha512 = "2631bhp784qng0ifbypsmvijn6kjfvkhq2335kdz8ix5qi3wb3lbpg94xjn1av2s6i95ygr5a4y9j1721dw6zdbywwh1m48by4qpa1h";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "commander-2.16.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.16.0.tgz";
        sha512 = "1xx0ldb0xa8kh9a9108nq09a5sx55k8i82037w4pw665a489qh1v9a0wk81ph1z94rfvi97k9q8x70ncp0ywdyydayx58lsaj9flmdi";
      };
    };
    "commander-2.17.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.17.1.tgz";
        sha512 = "21fbnprzkj53pjsp5wd7f5wa50jrirag11gq351jr8hhrib5gw62kylpvcddv3c2a1vcs1p8llq80wdnflh6lny3frnq7v7l6vi9wy0";
      };
    };
    "config-chain-1.1.11" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.11.tgz";
        sha1 = "aba09747dfbe4c3e70e766a6e41586e1859fc6f2";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "0q0fsr8bk1m83z0am0h2xn09vyfcf18adscxms8hclznwks1aihsisd96h8npx0idq5wwnypnqrkyk25m5d9zh3dk7rjs29nybc8bkc";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "3g1hqsahr1ks2kpvdxrwzr57fj90nnr0hvwwrw8yyyzcv3i11sym8zwibxx67bl1mln0acddrzpkkdjjxnc6n2cm9fazmgzzsl1fzrr";
      };
    };
    "editorconfig-0.13.3" = {
      name = "editorconfig";
      packageName = "editorconfig";
      version = "0.13.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/editorconfig/-/editorconfig-0.13.3.tgz";
        sha512 = "08ysphnfa9fynh31z9sbxq8nyw0v2w2q6xkvqpy13xr16mh58na9xrxjxj0r6vwr01xjna3jyz6njwbxw0dvyrq509y5fs2sm8fqj2s";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "eventemitter3-3.1.0" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-3.1.0.tgz";
        sha512 = "1q3lcjzcm6cva1avw6qkzynnk6rlcp0pblgxxliwry2z52rz9fy82wh630clfv12i64ygywca69hfbj3ki71hy1in94nqxzka32zwla";
      };
    };
    "exec-sh-0.2.2" = {
      name = "exec-sh";
      packageName = "exec-sh";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exec-sh/-/exec-sh-0.2.2.tgz";
        sha512 = "01xwgxaanmd0h0i1pvqy0fk6sqxmab59mjww1mzj3dc25zzrw4z7n7rcl5wd1y7s38lvgcg815qc700kw36ipd42jsf8vji7lkh518l";
      };
    };
    "follow-redirects-1.5.2" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.5.2.tgz";
        sha512 = "3q5f6qbamhz5sldh2nnaypkqcbdsig3njabqp919g3h056asgd1f1nn4lvpqj7pkbylqx16nkj9482f2pabjdllfq4agxgznfi0pjwj";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "ini-1.3.5" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz";
        sha512 = "1rjbvf1rg5ywhnba08sgagn2qf23lab330qrqmh7d891zap3xpxcyfyj1cblpf0f0rypglcfacybzyrpd4996aa1mbc820awa33k5j5";
      };
    };
    "lru-cache-3.2.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-3.2.0.tgz";
        sha1 = "71789b3b7f5399bec8565dda38aa30d2a097efee";
      };
    };
    "merge-1.2.0" = {
      name = "merge";
      packageName = "merge";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge/-/merge-1.2.0.tgz";
        sha1 = "7531e39d4949c281a66b8c5a6e0265e8b05894da";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "requires-port-1.0.0" = {
      name = "requires-port";
      packageName = "requires-port";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz";
        sha1 = "925d2601d39ac485e091cf0da5c6e694dc3dcaff";
      };
    };
    "semver-5.5.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.0.tgz";
        sha512 = "0h32zh035y8m6dzcqhcymbhwgmc8839fa1hhj0jfh9ivp9kmqfj1sbwnsnkzcn9qm3sqn38sa8ys2g4c638lpnmzjr0a0qndmv7f8p1";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
  };
in
{
  js-beautify = nodeEnv.buildNodePackage {
    name = "js-beautify";
    packageName = "js-beautify";
    version = "1.7.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/js-beautify/-/js-beautify-1.7.5.tgz";
      sha512 = "0x3s0bbw8f5d2i5jb08bd2dsxnf7w38fp7fj652cvp558b45mxyvy42zmghrmlyrmbk5d84d8maw4pqq3228jq0l7hkxb4fl415zs7l";
    };
    dependencies = [
      sources."abbrev-1.1.1"
      sources."bluebird-3.5.1"
      sources."commander-2.17.1"
      sources."config-chain-1.1.11"
      sources."editorconfig-0.13.3"
      sources."ini-1.3.5"
      sources."lru-cache-3.2.0"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."nopt-3.0.6"
      sources."proto-list-1.2.4"
      sources."pseudomap-1.0.2"
      sources."semver-5.5.0"
      sources."sigmund-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "jsbeautifier.org for node";
      homepage = http://jsbeautifier.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  uglify-js = nodeEnv.buildNodePackage {
    name = "uglify-js";
    packageName = "uglify-js";
    version = "3.4.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.4.6.tgz";
      sha512 = "371ivsaxzd64agmbvlpk8ldh68njnyk56yf0npr8ydzzkmq5ihg3q7hrv4b6r1rlc0v9sc0kjdid1wv8j58d7kdm6sk8fwwllpznl1v";
    };
    dependencies = [
      sources."commander-2.16.0"
      sources."source-map-0.6.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript parser, mangler/compressor and beautifier toolkit";
      homepage = "https://github.com/mishoo/UglifyJS2#readme";
      license = "BSD-2-Clause";
    };
    production = true;
    bypassCache = false;
  };
  prettier = nodeEnv.buildNodePackage {
    name = "prettier";
    packageName = "prettier";
    version = "1.14.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier/-/prettier-1.14.0.tgz";
      sha512 = "2ingl3myk748vm1jasphq35xya8hpgqz3kdz7pk5aq60rxnng2jih7rmvg0xw15bfs5k4cscal0zg8ifbydbs9pr22gvhclcq83dm1a";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier is an opinionated code formatter";
      homepage = https://prettier.io/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  tiddlywiki = nodeEnv.buildNodePackage {
    name = "tiddlywiki";
    packageName = "tiddlywiki";
    version = "5.1.17";
    src = fetchurl {
      url = "https://registry.npmjs.org/tiddlywiki/-/tiddlywiki-5.1.17.tgz";
      sha1 = "bd3311146ba67fb4beee9933dd2e6d55e92665ed";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "a non-linear personal web notebook";
      homepage = "https://github.com/Jermolene/TiddlyWiki5#readme";
      license = "BSD";
    };
    production = true;
    bypassCache = false;
  };
  sudo-prompt = nodeEnv.buildNodePackage {
    name = "sudo-prompt";
    packageName = "sudo-prompt";
    version = "8.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/sudo-prompt/-/sudo-prompt-8.2.0.tgz";
      sha512 = "13m223mxvgjpiwl8a3a7523id0amr1a3r69cdhgwjvz7jv36iypilab918h24m2p4nc3vjmmh3l58n9pih12x0d0vanfs8rabd6z4wz";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Run a command using sudo, prompting the user with an OS dialog if necessary";
      homepage = "https://github.com/jorangreef/sudo-prompt#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  qrcode-svg = nodeEnv.buildNodePackage {
    name = "qrcode-svg";
    packageName = "qrcode-svg";
    version = "1.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/qrcode-svg/-/qrcode-svg-1.0.0.tgz";
      sha1 = "25bddf0c06c7e546622f4b595a3553efa2647bce";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A simple QR Code generator in pure JavaScript";
      homepage = https://github.com/papnkukn/qrcode-svg;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  wait-port = nodeEnv.buildNodePackage {
    name = "wait-port";
    packageName = "wait-port";
    version = "0.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/wait-port/-/wait-port-0.2.2.tgz";
      sha1 = "d51a491e484a17bf75a947e711a2f012b4e6f2e3";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."chalk-1.1.3"
      sources."commander-2.17.1"
      sources."debug-2.6.9"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."ms-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Utility to wait for a TCP port to open.";
      homepage = "https://github.com/dwmkerr/wait-port#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  http-proxy = nodeEnv.buildNodePackage {
    name = "http-proxy";
    packageName = "http-proxy";
    version = "1.17.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/http-proxy/-/http-proxy-1.17.0.tgz";
      sha512 = "3z80svhb9hi5fawc8za5qn75lybr53646gfsqm2hkqss4pr186pp7k6f5jnjgw7vrkgjy4yzvb34729q6kvrikn4xgq9gfdg7xsgajd";
    };
    dependencies = [
      sources."debug-3.1.0"
      sources."eventemitter3-3.1.0"
      sources."follow-redirects-1.5.2"
      sources."ms-2.0.0"
      sources."requires-port-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "HTTP proxying for the masses";
      homepage = "https://github.com/nodejitsu/node-http-proxy#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  watch = nodeEnv.buildNodePackage {
    name = "watch";
    packageName = "watch";
    version = "1.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/watch/-/watch-1.0.2.tgz";
      sha1 = "340a717bde765726fa0aa07d721e0147a551df0c";
    };
    dependencies = [
      sources."exec-sh-0.2.2"
      sources."merge-1.2.0"
      sources."minimist-1.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Utilities for watching file trees.";
      homepage = https://github.com/mikeal/watch;
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = false;
  };
}