services:
  app:
    volumes:
      - .:/app
    build:
      context: .
    platform: linux/amd64
    environment:
      MODEL: TheBloke/samantha-mistral-instruct-7B-GGUF
      MODEL_FILE: samantha-mistral-instruct-7b.Q5_K_M.gguf
