version: "3.9"
services:
  server:
    image: corps/miniflux:latest
    networks:
      - traefik-public
      - db
    environment:
      BASE_URL: https://miniflux.kaihatsu.io/
      PORT: 8080
      ADMIN_PASSWORD_FILE: /run/secrets/miniflux_admin_password
      ADMIN_USERNAME: admin
      CREATE_ADMIN: 1
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.miniflux-http.rule=Host(`miniflux.kaihatsu.io`)
        - traefik.http.routers.miniflux-http.entrypoints=http
        - traefik.http.routers.miniflux-http.service=miniflux
        - traefik.http.services.miniflux.loadbalancer.server.port=8080
    command:
      - bash
      - -c
      - |
        set -e
        export DATABASE_URL="user=postgres host=db password=$$(cat /run/secrets/miniflux_postgres_password) dbname=miniflux sslmode=disable"
        miniflux -flush-sessions || true
        miniflux -migrate
        exec miniflux
    secrets:
      - miniflux_postgres_password
      - miniflux_admin_password

  db:
    image: postgres
    networks:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.miniflux-db == true
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
      - miniflux_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/miniflux_postgres_password
    secrets:
      - miniflux_postgres_password

volumes:
  miniflux_data:
    external: true

networks:
  traefik-public:
    external: true
  db:

secrets:
  miniflux_admin_password:
    external: true
  miniflux_postgres_password:
    external: true
