# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "commander-2.11.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.11.0.tgz";
        sha1 = "157152fd1e7a6c8d98a5b715cf376df928004563";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
  };
in
{
  "uglify-js-3.1.0" = nodeEnv.buildNodePackage {
    name = "uglify-js";
    packageName = "uglify-js";
    version = "3.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.1.0.tgz";
      sha1 = "92fae17b88dfbc3c394175a935044cdbcf4085ae";
    };
    dependencies = [
      sources."commander-2.11.0"
      sources."source-map-0.5.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript parser, mangler/compressor and beautifier toolkit";
      homepage = http://lisperator.net/uglifyjs;
      license = "BSD-2-Clause";
    };
    production = true;
  };
}