"""Migration

Revision ID: d1838805711a
Revises:
Create Date: 2024-04-14 05:57:51.156738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1838805711a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("refresh_token", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_account_id"), "user", ["account_id"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pending_edits", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("rev", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "path"),
    )
    op.create_index("file_sequence", "file", ["user_id", "sequence"], unique=False)
    op.create_index(
        op.f("ix_file_content_hash"), "file", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_file_sequence"), "file", ["sequence"], unique=False)
    op.create_table(
        "sync_cursor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.String(length=128), nullable=False),
        sa.Column(
            "namespace",
            sa.String(length=128),
            server_default="dropbox:list_folder",
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "namespace"),
    )
    op.create_table(
        "scheduled",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("schedule", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    op.create_index(
        "schedule_sequence", "scheduled", ["user_id", "schedule"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("schedule_sequence", table_name="scheduled")
    op.drop_table("scheduled")
    op.drop_table("sync_cursor")
    op.drop_index(op.f("ix_file_sequence"), table_name="file")
    op.drop_index(op.f("ix_file_content_hash"), table_name="file")
    op.drop_index("file_sequence", table_name="file")
    op.drop_table("file")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_account_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
