version: '3.8'
services:
  app:
    image: corps/bensrs:latest
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bensrs-http.rule=Host(`bensrs.kaihatsu.io`)
        - traefik.http.routers.bensrs-http.entrypoints=http
        - traefik.http.services.bensrs.loadbalancer.server.port=3000
      placement:
        constraints: 
          - node.role == manager
          - node.labels.bensrs == true
    volumes:
      - bensrs_app_data:/app/data
    secrets:
      - bensrs-secret

secrets:
  bensrs-secret:
    external: true

networks:
  traefik-public:
    external: true
    
volumes:
  bensrs_app_data:
    driver: local
