version: "3.8"
services:
  app:
    image: corps/jupyter
    networks:
      - traefik-public
      - mistral
    command:
      - "start-notebook.sh"
      - "--NotebookApp.password='argon2:$$argon2id$$v=19$$m=10240,t=10,p=8$$2NWJkwYTtxatvj+4Tyz61Q$$0U1dMk+Wvoq5tFt9Z/JianidtEzsbAKbvxZjehOgtgo'"
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.jupyter-http.rule=Host(`jupyter.kaihatsu.io`)
        - traefik.http.routers.jupyter-http.entrypoints=http
        - traefik.http.services.jupyter.loadbalancer.server.port=8888
      placement:
        constraints:
          - node.role == manager
          - node.labels.jupyter == true
    volumes:
      - jupyter_app_data:/home/jovyan/work
      - jupyter_conda_env:/opt/conda
      - jupyter_cache_dir:/home/jovyan/.cache
      - jupyter_local_dir:/home/jovyan/.local
    secrets:
      - hugging_face_token

networks:
  traefik-public:
    external: true
  mistral:
    external: true

volumes:
  jupyter_app_data:
    driver: local
  jupyter_conda_env:
    driver: local
  jupyter_cache_dir:
    driver: local
  jupyter_local_dir:
    driver: local

secrets:
  hugging_face_token:
    external: true
