version: "3.8"
services:
  app:
    image: corps/loogle
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.loogle-http.rule=Host(`loogle.kaihatsu.io`)
        - traefik.http.routers.loogle-http.entrypoints=http
        - traefik.http.routers.loogle-http.service=loogle
        - traefik.http.services.loogle.loadbalancer.server.port=8088
      placement:
        constraints:
          - node.labels.loogle == true

    volumes:
      - lake_cache:/loogle/.lake

networks:
  traefik-public:
    external: true

volumes:
  lake_cache:
    driver: local
