version: "3.8"
services:
  agent:
    image: corps/ngrok:latest
    networks:
      - traefik-public
    deploy:
      replicas: 2
    secrets:
      - ngrok-auth
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p ~/.config/ngrok/
        ngrok config add-authtoken "$$(cat /run/secrets/ngrok-auth)"
        ngrok config check
        exec ngrok http traefik_traefik:80 --url https://default.internal --pooling-enabled

  mitm_agent:
    image: corps/ngrok:latest
    networks:
      - traefik-public
    deploy:
      replicas: 2
    secrets:
      - ngrok-auth
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p ~/.config/ngrok/
        ngrok config add-authtoken "$$(cat /run/secrets/ngrok-auth)"
        exec ngrok tcp traefik_traefik:1080 --url tcp://socks.internal:1080 --pooling-enabled

networks:
  traefik-public:
    external: true

secrets:
  ngrok-auth:
    external: true
