version: "3.8"
services:
  agent:
    image: corps/ngrok:latest
    networks:
      - traefik-public
    deploy:
      mode: global
    secrets:
      - ngrok-auth
    command:
      - bash
      - -c
      - |
        set -e
        mkdir -p ~/.config/ngrok/
        ngrok config add-authtoken "$$(cat /run/secrets/ngrok-auth)"
        exec ngrok http traefik_traefik:80 --url https://*.kaihatsu.io --pooling-enabled

networks:
  traefik-public:
    external: true

secrets:
  ngrok-auth:
    external: true
