#! /usr/bin/env bash
set -e
set -o pipefail

branch=${BRANCH:-master}
echo "Running for branch $branch"

git pull
$@ || true

while true; do
  sleep 10
  git fetch

  if git log HEAD..origin/$branch | grep commit; then
    git pull
    $@ || true
  fi
done
